name: django-model
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - asgiref=3.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=39.0.0
  - django=5.1.2
  - flatbuffers=24.3.25
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gast=0.4.0
  - giflib=5.2.2
  - google-auth=2.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.46.3
  - h2=4.1.0
  - h5py=3.9.0
  - hdf5=1.14.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=58.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2024.2.1
  - joblib=1.4.2
  - jpeg=9e
  - keras=2.10.0
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libdeflate=1.22
  - libffi=3.4.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.43
  - libprotobuf=3.20.3
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.6
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pillow=10.4.0
  - pip=24.2
  - propcache=0.2.0
  - protobuf=3.20.3
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pyjwt=2.9.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.9.0
  - python-flatbuffers=24.3.25
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - pyu2f=0.1.5
  - re2=2024.07.02
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.9
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.47.0
  - sqlparse=0.5.1
  - tbb=2021.7.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.5.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - werkzeug=3.0.6
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yarl=1.16.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
